/**
 * @file audit.types.ts
 * @path apps/frontend/src/lib/audit.types.ts
 * @description Tipe data audit log frontend.
 * @see docs/CODEBASE.md — dokumentasi arsitektur lengkap SIMRS
 */

// Audit Log Types - replicate from @prisma/client for frontend use
// Do NOT import @prisma/client in frontend - use these types instead

export enum AuditAction {
  // Authentication
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  RESET_PASSWORD = 'RESET_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  
  // User Management
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  ROLE_CHANGE = 'ROLE_CHANGE',
  
  // Patient
  PATIENT_REGISTER = 'PATIENT_REGISTER',
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  PATIENT_DELETE = 'PATIENT_DELETE',
  
  // Medical Records
  DIAGNOSIS_ADD = 'DIAGNOSIS_ADD',
  MEDICAL_RECORD_UPDATE = 'MEDICAL_RECORD_UPDATE',
  PRESCRIPTION_ADD = 'PRESCRIPTION_ADD',
  LAB_RESULT_UPLOAD = 'LAB_RESULT_UPLOAD',
  
  // Appointment
  APPOINTMENT_BOOK = 'APPOINTMENT_BOOK',
  APPOINTMENT_RESCHEDULE = 'APPOINTMENT_RESCHEDULE',
  APPOINTMENT_CANCEL = 'APPOINTMENT_CANCEL',
  
  // Pharmacy
  MEDICINE_STOCK_ADD = 'MEDICINE_STOCK_ADD',
  MEDICINE_STOCK_UPDATE = 'MEDICINE_STOCK_UPDATE',
  MEDICINE_OUT = 'MEDICINE_OUT',
  
  // System
  DATABASE_BACKUP = 'DATABASE_BACKUP',
  DATABASE_RESTORE = 'DATABASE_RESTORE',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SETTING_UPDATE = 'SETTING_UPDATE',
  
  OTHER = 'OTHER',
}

export enum AuditModule {
  AUTH = 'AUTH',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  PATIENT = 'PATIENT',
  APPOINTMENT = 'APPOINTMENT',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  PHARMACY = 'PHARMACY',
  BILLING = 'BILLING',
  RADIOLOGY = 'RADIOLOGY',
  LABORATORY = 'LABORATORY',
  QUEUE = 'QUEUE',
  SYSTEM = 'SYSTEM',
  OTHER = 'OTHER',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
}
