FROM nginx:1.27-alpine

RUN apk add --no-cache openssl wget

COPY docker/nginx/conf.d/ /etc/nginx/conf.d/
COPY docker/nginx/snippets/ /etc/nginx/snippets/
COPY docker/scripts/nginx-entrypoint.sh /docker-entrypoint.d/40-simrs-entrypoint.sh
RUN chmod +x /docker-entrypoint.d/40-simrs-entrypoint.sh
